apiVersion: v1
kind: Service
metadata:
  name: {{ include "dgs.coordinator.name" . }}-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dgs.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: coordinator-nodeport
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.coordinator.httpService.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.coordinator.httpService.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: NodePort
  sessionAffinity: {{ .Values.coordinator.httpService.sessionAffinity }}
  externalTrafficPolicy: {{ .Values.coordinator.httpService.externalTrafficPolicy | quote }}
  ports:
    - protocol: TCP
      port: {{ .Values.coordinator.httpService.port }}
      targetPort: http-port
  selector:
    {{- include "dgs.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: coordinator
