{{- range $i, $e := until (.Values.serving.workerNum | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dgs.serving.name" $ }}-nodeport-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "dgs.labels" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: serving-nodeport-{{ $i }}
  annotations:
    {{- if $.Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if $.Values.serving.httpService.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.serving.httpService.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: NodePort
  sessionAffinity: {{ $.Values.serving.httpService.sessionAffinity }}
  externalTrafficPolicy: {{ $.Values.serving.httpService.externalTrafficPolicy | quote }}
  ports:
    - protocol: TCP
      port: {{ $.Values.serving.httpService.port }}
      targetPort: http-port
  selector:
    {{- include "dgs.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: serving
    {{ include "dgs.label.group" $ }}/worker: serving-{{ $i }}
{{- end }}