apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: ${your_job_name}
  namespace: ${your_namespace}
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - pip install scipy && cd /root/data/examples/tf/ego_sage;
              cd ../../data && python cora.py && cd - && python train_supervised.py
            image: graphlearn/graphlearn
            imagePullPolicy: Always
            name: tensorflow
            resources:
              limits:
                cpu: "4"
                memory: 16Gi
            volumeMounts:
            - mountPath: /root/data/
              name: ${your_volume}
            workingDir: /root/
          volumes:
          - name: ${your_volume}
            persistentVolumeClaim:
              claimName: ${your_pvc_name}
